### ISSUE TITLE
GLX support

### ISSUE THREAD

**Issue by 4nte** [weichuntsai0217/xserver#2]
I followed the example steps provided in the README.
I managed to start the xserver service, run my docker image, setup auth cookie in my app container.

When I start the GUI app, I get: **GLX is not supported**

Do you have any idea on how to enable GLX in this setup?

**Comment by 4nte** [comment]
I managed to enable GLX support by adding providing `+extension GLX` to Xvfb

**Comment by weichuntsai0217** [comment]
Hi 4nte,
Thanks for your bug report. Would you mind sharing how you do `+extension GLX` in my `xserver` container?
I would appreciate that.

**Comment by 4nte** [comment]
Following enables the GLX extension:
```
Xvfb $DISPLAY -auth ${HOME}/.Xauthority +extension GLX -dpi $SCREEN_DPI -screen ${DISPLAY:1:1} $SCREEN_SIZE > /dev/null &
```

Unrelated to this - My GUI app would show as a black window due to an error related with MIT-SHM. I added `--ipc=host` arg to `docker run` when running my GUI app docker image and it resolved the issue.
